name: Build and Deploy to Cloud Run

on: push

env:
  PROJECT_ID: 'letterboxd-api'
  REGION: 'us-east1'
  SERVICE: 'letterboxd-api'

jobs:
  build:
    name: Build Java Spring Application
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Compile Application to Native Image (Main)
        if: ${{ github.ref_name == 'main' }}
        run: |
          APP_NAME=letterboxd-api
          ./gradlew --no-daemon nativeCompile

      - name: Compile Application to Native Image (Develop)
        if: ${{ github.ref_name == 'develop' }}
        run: |
          APP_NAME=letterboxd-api
          ./gradlew --no-daemon nativeCompile --quick-build-native

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: Build and Push Container
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dkr-repo/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Deploy to Cloud Run (Main)
        if: ${{ github.ref_name == 'main' }}
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: '${{ env.PROJECT_ID }}'
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dkr-repo/${{ env.SERVICE }}:${{ github.sha }}'

      - name: Deploy to Cloud Run (Develop)
        if: ${{ github.ref_name == 'develop' }}
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: '${{ env.PROJECT_ID }}'
          service: '${{ env.SERVICE }}-develop'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dkr-repo/${{ env.SERVICE }}:${{ github.sha }}'

      - name: Show Output
        run: |-
          echo ${{ steps.deploy.outputs.url }}